language: cpp
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    packages:
    - libcurl3-gnutls
    - libcurl4-gnutls-dev
    - libxml2
    - libxml2-dev
    - zlib1g-dev
script:
  - ./ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j4
  - ctest -V
notifications:
  email: false
