language: cpp
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    packages:
    - libxml2
    - libxml2-dev
    - zlib1g-dev
script:
  - ./ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
#  - ctest -V
notifications:
  email: false
